infra: remove old workflows and add test upstream sync workflow

diff --git a/.github/workflows/sync-upstream-releases.yaml b/.github/workflows/sync-upstream-releases.yaml
--- a/.github/workflows/sync-upstream-releases.yaml
+++ b/.github/workflows/sync-upstream-releases.yaml
@@ -22,10 +22,22 @@ jobs:
       # 1. Fetch the latest tag from Chainguard fork
       - name: Get latest upstream release
         id: upstream
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          LATEST_TAG=$(curl -s https://api.github.com/repos/chainguard-forks/ingress-nginx/tags | jq -r '.[0].name')
-          echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
-          echo "Latest tag in Chainguard: $LATEST_TAG"
+          # Fetch the latest tag from the Chainguard fork of ingress-nginx
+          RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/chainguard-forks/ingress-nginx/tags)
+          
+          # Check if the response is a valid JSON array
+          if echo "$RESPONSE" | jq -e 'type == "array"' > /dev/null; then
+            LATEST_TAG=$(echo "$RESPONSE" | jq -r '.[0].name')
+            echo "tag=$LATEST_TAG" >> "$GITHUB_OUTPUT"
+            echo "Latest tag in Chainguard: $LATEST_TAG"
+          else
+            echo "API GitHub returned an error instead of a tag list:"
+            echo "$RESPONSE" | jq .
+            exit 1
+          fi
 
       # 2. CLONE CHAINGUARD REPOSITORY
       - name: Checkout upstream tag
